### ISSUE TITLE
RFC: tutorial on EVM patterns in Solana

### ISSUE THREAD

**Issue by zkwarlock** [solana-dev-adv/solana-cookbook#163]
I'm looking to write a guide on:
1. Maps
  - How to emulate with PDAs

2. Factory smart contracts:
  - As smart contracts cannot be deployed in Solana using CPI, the result is a monolithic design.
  -  PDAs in place of `keccak256(abi.encodePacked())`

3. Arrays
  - Size and compute limit on storing arrays in a single account
  - Emulate arrays with PDAs
  - Iterating on PDA arrays using remaining accounts

4. Re-entrancy and callbacks: 
  - Since `Reentrancy is currently limited to direct self recursion capped at a fixed depth`, EVM's callback pattern (A -> B -> A) cannot be implemented. I instead propose a sandwich pattern (A -> B -> C).
  - Calling your own smart contract: To CPI or call internally

Looks good? Looking for feedback before starting work.

**Comment by jacobcreech** [comment]
Hey @zkwarlock 

Looks like a good guide, but not sure if everything belongs in the cookbook

You could write an ingredient completely on the different ways to do account maps. I'll make an issue for that off of here

For 2, could you expand? Sounds interesting

For 3, Arrays could be a decent ingredient as well. I am not sure if you could put both in a maps and arrays ingredient, but would be great if possible

For 4, we do need a CPI core concept written. This kind of stuff can be explored there. Creating an issue off of that

**Comment by jacobcreech** [comment]
Created both #167 and #166 Off of this

**Comment by jacobcreech** [comment]
Closing to move to the new issues
