### ISSUE TITLE
[Guide] Account Maps

### ISSUE THREAD

**Issue by jacobcreech** [solana-dev-adv/solana-cookbook#167]
Maps are often a problem people have when coming to Solana

We need to explain the multiple ways of creating account maps, as well as give examples of each.

For example:
- Explain how to use multiple accounts to create an account map
- Show how to use deriving PDAs to create a map

**Comment by sayantank** [comment]
@jacobcreech Can I take this up? I'm a little unsure about what you mean in the first point though

**Comment by sayantank** [comment]
On it! Thanks for the explanation!

**Comment by FrankC01** [comment]
Has anyone benchmarked 'verifying' the merkle proof as far as CU go? Just curious...
