### ISSUE TITLE
Signing using both wallet and key-pairs

### ISSUE THREAD

**Issue by charles-e** [solana-dev-adv/solana-cookbook#178]
For web-app development you primarily sign using the wallet(adapter) since that's where the real "money" comes from but some transactions need other signers (key-pairs). For example to create an account requires the signature of the owner (which will normally be the wallet) but also the actual identity key-pair for the account.

**Comment by charles-e** [comment]
So you have strung together several instructions in a single transaction `txn` and array of other keypairs `signers`.
```
    txn.feePayer = wallet.publicKey;
    signers.map((signer)=>{txn.partialSign(signer)});

    let signed = await wallet.signTransaction(txn);
    console.log(signed);
    let buf = signed.serialize();
    // can't use sendTransaction since it expects a non-empty array of signers
    let send = await connection.sendRawTransaction(buf);
    console.log(send);
```

**Comment by jacobcreech** [comment]
Hey @charles-e, we appreciate the contribution

However, I think this is already covered. Basic Transactions has multiple wallet-adapter references for sending transactions using the wallet-adapter's sendTransaction method. Ideally we'd have wallet-adapter be used everywhere, but we're still working on that.

You could totally do something like this in the offline transactions reference section though
