### ISSUE TITLE
Get the owner of an NFT will just get the Token program account, not the actual owner of the NFT

### ISSUE THREAD

**Issue by stephenwilliams1990** [solana-dev-adv/solana-cookbook#181]
The docs outlined at the following link will simply return the Token Program, instead of the users wallet that actually holds a certain NFT, as presumably would be desired. (Link: https://solanacookbook.com/references/nfts.html#get-the-owner-of-an-nft).

The owner as defined in the Solana docs is generally a "base-58 encoded Pubkey of the program this account has been assigned to", which in this case is the Token program.

**Comment by jacobcreech** [comment]
Thanks for the catch! Fixed in #182
