### ISSUE TITLE
[Core Concepts] Want to add Solana Overview Mindmap Diagram - Requesting Advice 

### ISSUE THREAD

**Issue by morektz** [solana-dev-adv/solana-cookbook#222]
I have made a mindmap which is basically an overall summary of Solana. You can find that [HERE](https://raw.githubusercontent.com/morektz/SolanaLearningMindMaps/main/pix/SolanaProgramsOverview.png) and the repository with the code can be found [HERE](https://github.com/morektz/SolanaLearningMindMaps)

Initially I had made this diagram and posted in the following discords - [Solana Official](https://discord.com/channels/428295358100013066/428295358100013069/933450246019760128), [Buildspace](https://discord.com/channels/869321815833575434/911143763013959720/933449527388696617) & [Questbook](https://discord.com/channels/847237372903030844/918886067644538891/933449620292517888). This was viewed around 300 time approximately in the past two days, You can see the statistics [HERE](https://ibb.co/rFL1ZnZ)

**I am seeking advice and answers to the following questions.** 

I am opening this issue to ask the following questions 
1. Do you think it is worthy of being included in Solana Cook Book ? 
2. If it is worthy of being added, please let me know if the pic needs any changes ?
3. I have made a fork and using the online code editor - [GITPOD](https://www.gitpod.io/), which is a basically an ephemeral cloud container for development, the problem I have is that the page keeps reloading over and over again, I want to know how do I stop that ? 

Once I get this information, I will assign this issue to myself and make a PR according to the contribution guidelines.

**Comment by jacobcreech** [comment]
@morektz I think this is a great diagram!

Really cool how you can create mind maps with this to better explain the core native programs of Solana

However, I am not sure if this belongs on the current cookbook. I'd recommend writing an article about it and submitting to soldev.app and go from there. 

While the programs are useful to know, cookbook is trying to avoid separating the programs too much from just all programs. They're just open capabilities that you can use today. A new developer coming to Solana will likely not care.

**Comment by morektz** [comment]
@jacobcreech Thanks for taking the time to read this issue so quickly. 

It definitely makes sense not to confuse the n00bz (like myself). I do use soldev.app constantly, since its an excellent resource for learning , will look into it. Peace !
