### ISSUE TITLE
[Recipe] NFTs

### ISSUE THREAD

**Issue by jacobcreech** [solana-dev-adv/solana-cookbook#23]
The NFT Recipe should contain the following:

Todo:
- How to get Mint Addresses generated given a Candy Machine address

Completed:
- ~~How to create a NFT token(just a single token with no mint authority~~
- ~~How to create a NFT using Metaplex~~
- ~~How to get NFT owner given a mint~~
- ~~Get NFT Metadata~~

**Comment by sayantank** [comment]
Hi, I would like to take up this recipe, but I wouldn't call myself an expert in Solana. I hope that isn't an issue.

**Comment by Jacob-CG** [comment]
@sayantank Best to run the code in a separate repo. They're just examples of paste-able code.

No expertise required for Adding Recipes! I learned a lot trying to write some of these. I'll assign this to you. Let me know of any questions or progress.

As a side note, make sure you use metaplex's js libraries when doing the metaplex-related snippets

**Comment by hogyzen12** [comment]
Im happy to assist with this as required. Have it bookmarked. sayantank reach out if u need anything !

**Comment by sayantank** [comment]
Thanks guys! Means a lot. I'll get some code ready ASAP 🤓

**Comment by sayantank** [comment]
I have a doubt, the first task requires us to create a **single** NFT token with no mint authority. So does that mean I create a `Mint` account and then use it to **mint** a single token to a user's associated account?

And, the `spl-token.Token.createMint()` function seems to require a public key as the **mint authority**. Am I missing something?

This is the piece of code error-ing out, 
```
  // Create the Mint for our NFT
  const mint = await spl.Token.createMint(
    connection,
    userKeypair,
    null, <=
    null,
    0,
    spl.TOKEN_PROGRAM_ID
  );

  // Get the assosciated account for the user
  const userAssociatedAccount = await mint.getOrCreateAssociatedAccountInfo(
    userKeypair.publicKey
  );

  await mint.mintTo(userAssociatedAccount.address, null, [], 1);

  const newInfo = await mint.getAccountInfo(userAssociatedAccount.address);
  console.log("balance: ", newInfo.amount);
 ```
and the error being, 
```
TypeError: Cannot read property 'toBuffer' of null
    at pubkeyToBuffer (/home/sayantank/workspace/solana/cookbook-test/node_modules/@solana/spl-token/lib/index.cjs.js:73:39)
    at Function.createInitMintInstruction (/home/sayantank/workspace/solana/cookbook-test/node_modules/@solana/spl-token/lib/index.cjs.js:936:24)
    at Function.createMint (/home/sayantank/workspace/solana/cookbook-test/node_modules/@solana/spl-token/lib/index.cjs.js:253:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async main (/home/sayantank/workspace/solana/cookbook-test/test.js:21:16)
    at async runMain (/home/sayantank/workspace/solana/cookbook-test/test.js:43:5)
```

---

Also, I did try minting with the `user` as the mint authority, and it seemed to be working.

**Comment by sayantank** [comment]
Another small query, does the Metaplex task requires us to mint a NFT using the Metaplex frontend or is there a npm library that I'm unaware about still?

Also, do you guys mind sharing your Discord, I could ask my queries there if this is too much hassle?

**Comment by Jacob-CG** [comment]
@sayantank The first issue is creating an NFT without a mint authority. Let me expand on that.

1. Create an NFT with a mint authority
2. Remove the mint authority so no more can be minted and it can actually be an NFT

Here's an example with the CLI: https://spl.solana.com/token#example-create-a-non-fungible-token
It is also possible with TS

Let me know if you have any other questions!

**Comment by Jacob-CG** [comment]
On your second question, the metaplex js sdk is definitely what you should be using. Please contact me at JacobCG#3467 and I'll get you added to a discord

**Comment by sayantank** [comment]
I put in a PR for the first task mentioned. Do let me know if I missed something!

**Comment by ADBalici** [comment]
I can take this one (to start with) if nobody minds:

- How to get NFT owner given a mint

Qs:
- Sometime the current owner is a PDA. These are cases, for example, in which the previous owner listed the token on a marketplace. Do we want guidelines of how we can trace the ownership back to the previous non-PDA owner?

**Comment by Jacob-CG** [comment]
@ADBalici 
Guidelines for both would be fantastic!

**Comment by ADBalici** [comment]
How about this?

https://github.com/solana-dev-adv/solana-cookbook/pull/106

**Comment by Jacob-CG** [comment]
@ADBalici Awesome job. Great little tricks like these are what usually trip people up developing. Thanks for the contribution!

**Comment by ADBalici** [comment]
Thanks! Will come back with other some other PRs in the upcoming days.

**Comment by abishekk92** [comment]
Looks like all the individual subtasks have been addressed and merged. Can we close this issue so that potential contributors don't get confused?

**Comment by jacobcreech** [comment]
@abishekk92 still have `How to get Mint Addresses generated given a Candy Machine address` I believe.

**Comment by abishekk92** [comment]
Oh, I didn't notice that. Anyway, I can pick that up

**Comment by ashish4x** [comment]
HI @jacobcreech , Can I complete this recipe task on `How to get Mint Addresses generated given a Candy Machine address` ?

**Comment by jacobcreech** [comment]
@ashish4x yes, please do!

**Comment by ashish4x** [comment]
> @ashish4x yes, please do!

I've been trying to setup this locally, but It's not working. I'm getting a blank page every time. Could you please look into that?

**Comment by jacobcreech** [comment]
@ashish4x It seems one of the dependabot upgrades broke it. I reverted and it seems to work fine now. Let me know if it doesn't work.

**Comment by ashish4x** [comment]
Hi @jacobcreech, I made a PR for the NFT mint addresses recipe. Let me know if I missed anything

**Comment by jacobcreech** [comment]
@ashish4x Added a review. The `contributors` sections may get removed soon, as it seems to be pretty bugged at this time in vuepress. May change to a different standard of credit soon.
