### ISSUE TITLE
[sacffold] solana-base-app

### ISSUE THREAD

**Issue by UjjwalGupta49** [solana-dev-adv/solana-cookbook#230]
Hey, I'm contributing solana-base-app to the Cookbook, It's a base-level application that helps beginners get up and running fast, avoiding all complexities.
It includes most of the basic features such as
1) Wallet connection (Using wallet-adapter)
2) Getting wallet balance (Using Web3.js)
3) Airdropiing SOL into the wallet
----------------------------------------------
An npx package also live, try it using
npx solana-base-app react my-app

> All the packages would installed with the npx command
---------------------------------------------
For documentation and roadmap checkout the GitHub repository: [solana-base-app](https://github.com/UjjwalGupta49/solana-base-app)

**Comment by UjjwalGupta49** [comment]
@jacobcreech kindly help, me cointribute

**Comment by jacobcreech** [comment]
@UjjwalGupta49 I love the work, but I don't believe this belongs in the Solanacookbook.

I would suggest you submit to soldev.app instead under scaffolds!

**Comment by UjjwalGupta49** [comment]
Already done Sir, 
Thank you
