### ISSUE TITLE
Link in the Retrying Transactions article seems outdated

### ISSUE THREAD

**Issue by josephtaylor** [solana-dev-adv/solana-cookbook#237]
The first link in the [Customizing Rebroadcast Logic section](https://solanacookbook.com/guides/retrying-transactions.html#customizing-rebroadcast-logic) seems to be outdated.

"within reasonable bounds" links to: https://github.com/solana-labs/solana/blob/master/validator/src/main.rs#L1316-L1332

Would be happy to submit a PR to update it but I'm not sure which lines it's supposed to point to, maybe the ones for the RPC parameters related to `maxRetries`? maybe:

[https://github.com/solana-labs/solana/blob/master/validator/src/main.rs#L1245-L1261](https://github.com/solana-labs/solana/blob/master/validator/src/main.rs#L1245-L1261)

I could be completely wrong on this, if so sorry!

**Comment by jacobcreech** [comment]
@josephtaylor It seems like the code has been updating, breaking the link. Probably best to link to a specific commit time instead of master. You're welcome to update it!
