### ISSUE TITLE
[Recipe] Programs

### ISSUE THREAD

**Issue by Jacob-CG** [solana-dev-adv/solana-cookbook#24]
An excellent recipe would be a program cheatsheet containing at least the following

- How to get clock in a program
- How to do CPI(With transfer example)
- Create a PDA
- Reading Account
- Verify Account

**Comment by sunguru98** [comment]
Hey, if you don't mind, may I take up on this issue please? Would love to contribute on this :)

**Comment by sunguru98** [comment]
Hey sorry, I was a bit packed on the schedule so couldn't revert on this. I'm back and just wanna make sure if no one is working on it, if yes, may I know the topics that have been merged already @Jacob-CG ?

**Comment by Jacob-CG** [comment]
@sunguru98 None has done as of today. Go ahead and run with it!

**Comment by sunguru98** [comment]
Thanks @Jacob-CG
