### ISSUE TITLE
Add back names of contributors under the section(s) they contributed to

### ISSUE THREAD

**Issue by rasreee** [solana-dev-adv/solana-cookbook#249]
Crediting the contributors by listing them like how it was before makes them feel proud & acknowledged for their contributions! 

I noticed my name was taken off of the content I contributed (https://solanacookbook.com/references/keypairs-and-wallets.html#connecting-to-a-wallet) and it made me sad :(

![image](https://user-images.githubusercontent.com/21317871/154820793-00bca7d3-48a2-452a-944c-c39d97a450d7.jpeg)

If we're going to credit contributors at all under each section, can we make sure to include everyone?

**Comment by jacobcreech** [comment]
@rasreee While I agree with your sentiment, there seems to be a bug in Vuepress with these contributors. I've been meaning to disable it until the big is fixed. You're welcome to look into the fix if you'd like

**Comment by rasreee** [comment]
Ahhh, thanks for the clarification!
