### ISSUE TITLE
[Component] Code Preview

### ISSUE THREAD

**Issue by Jacob-CG** [solana-dev-adv/solana-cookbook#25]
We're looking to incorporate a code preview component that will allow people to switch between a code preview and the full source code.

The code preview be like [MUI's code preview](https://mui.com/components/buttons/#basic-button) with a few changes.

1. Source language should always be viewable
2. Button to switch between preview/full source on specific language selected
3. Button will switch out code provided with file

A quick mockup would be like this:
<img width="717" alt="Screen Shot 2021-11-30 at 4 07 52 PM" src="https://user-images.githubusercontent.com/82475023/144135960-19cc5438-3d38-4210-a8e1-21c87e23c2c7.png">

The UX flow would be as follows:

1. Clicking the `TS` or other language button would switch to your language choice.
2. Clicking the `< >` would switch between full code or just a preview for the language choice. For the above mockup, the preview would be just `let keypair = Keypair.generate();`
3. Switching between can be grabbing from two different files, such as `generate-keypair.preview.ts` and `generate-keypair.full.ts`.

**Comment by timhanlon** [comment]
I'll take a stab at this.

**Comment by Jacob-CG** [comment]
> I'll take a stab at this.

Awesome! Look forward to seeing what is made. If you have any questions, please let me know.
