### ISSUE TITLE
Pull all the NFTs for a public address in a generic way

### ISSUE THREAD

**Issue by pcibraro** [solana-dev-adv/solana-cookbook#254]
For applications that require pulling user's nfts in a generic manner for performing different things (e.g. authorization), it would be useful to have a recipe that does not depend on candy machine and just returns your tokens and the associated metadata.  I was able to come up with a script for doing that, and I would like to contribute it here.

**Comment by jacobcreech** [comment]
@pcibraro Do it! I'd love to see this contribution.

**Comment by Dewnish** [comment]
Very interested in this!

**Comment by pcibraro** [comment]
Awesome. I just sent a pull request. Feel free to review and let me know your feedback/comments. https://github.com/solana-dev-adv/solana-cookbook/pull/256

**Comment by jacobcreech** [comment]
Closing in reference to https://github.com/solana-dev-adv/solana-cookbook/pull/256#issuecomment-1051137992
