### ISSUE TITLE
[Guide] Debugging

### ISSUE THREAD

**Issue by jacobcreech** [solana-dev-adv/solana-cookbook#26]
A recipe defining how to debug programs would be greatly helpful to new developers

Recipe should have at least the following:

- Debugging transaction failure
- Creating custom program error codes
- Logging in a Program

**Comment by FrankC01** [comment]
With details of using `solana-test-validator` and `solana_program_test::ProgramTest` and how they differ?

**Comment by Jacob-CG** [comment]
@FrankC01 Examples of both would be great

**Comment by FrankC01** [comment]
@Jacob-CG I'll see if I can manage the time to do this one and let you know ASAP

**Comment by 0xdeepmehta** [comment]
@jacobcreech Can I take this up, if no one is working on it?

Planning to work on:
- Debugging transaction failure
- Creating custom program error codes
- Logging in a Program

**Comment by jacobcreech** [comment]
@0xdeepmehta sure! I'll add you

**Comment by 0xdeepmehta** [comment]
awesome thanks :)

**Comment by 0xdeepmehta** [comment]
@jacobcreech Just have one small question, should I add a new section `Debugging ` in the `Anchor` Recipe itself?

**Comment by jacobcreech** [comment]
@0xdeepmehta No, this would be an entire new page under ingredients with the similar ingredient format

It should also contain both anchor and native information. Ideally the text should be generic enough and the code switchable like the other sections

**Comment by 0xdeepmehta** [comment]
@jacobcreech what is meant by **native information**?

**Comment by jacobcreech** [comment]
@0xdeepmehta both native programs and anchor should be covered

**Comment by FrankC01** [comment]
Rather than sit on this, I'd be happy to at least getting the unit testing/debugging pieces done.

Like all references and guides I assume they can be incrementally extended for things like Anchor nuances, etc.?

Say the world and I'll re-assign myself

**Comment by jacobcreech** [comment]
@FrankC01 Sounds good, go ahead!
