### ISSUE TITLE
[Design] Logo

### ISSUE THREAD

**Issue by Jacob-CG** [solana-dev-adv/solana-cookbook#27]
There's currently no logo for the cookbook. Open to any suggestions

**Comment by silvestrevivo** [comment]
This is the first idea that came to my mind ![image](https://user-images.githubusercontent.com/10574041/144389042-ef8eabde-66cf-4b2a-95e8-4b2ca7027a2d.jpeg)
![image](https://user-images.githubusercontent.com/10574041/144389090-42ed38f6-f5f7-4d24-8edb-160237b07fb5.jpeg)

The logo it becomes tree books on top of each other in perspective. 🙂

**Comment by bfriel** [comment]
Related: we should probably add some metatags that make this easier to share. I've found that setting [summary cards with large images on Twitter](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image) really drives engagement. Right now we just have a link with no image.

![Screen Shot 2021-12-02 at 9 19 01 PM](https://user-images.githubusercontent.com/15083324/144549704-6bdae2cb-ab20-4a0d-8c47-813b6099cdb4.png)

**Comment by silvestrevivo** [comment]
@Jacob-CG how is the status of this currently? I got this link https://superteam.fun/500-bounties/solana-cookbook-logo-design-bounty but I didn't find any reference in the Discord server to this.

**Comment by Jacob-CG** [comment]
@silvestrevivo They completed the bounty. We will probably have a logo pretty soon. Will go ahead and close this
