### ISSUE TITLE
[Snippet] Memos

### ISSUE THREAD

**Issue by Jacob-CG** [solana-dev-adv/solana-cookbook#28]
Adding a memo to a transaction in the `Basic Transactions` section would be helpful.

- How to add a memo to a transaction

**Comment by silvestrevivo** [comment]
Reading the docs and after checking several answer on the Discord server, it seems we can add a memo to a transaction on this way:

```
const transferTransaction = new Transaction()
  .add(SystemProgram.transfer({
    fromPubkey: fromKeypair.publicKey,
    toPubkey: toKeypair.publicKey,
    lamports: lamportsToSend
  }))

  transferTransaction.add(
    new TransactionInstruction({
      keys: [{ pubkey: fromKeypair.publicKey, isSigner: true, isWritable: true }],
      data: Buffer.from('data to send in transaction', 'utf8'),
      programId: SystemProgram.programId,
    })
  )
```
`transferTransaction` is taken from the cookbook (Basic transactions). I will test it out on devnet to be sure it is working before open a PR.
