### ISSUE TITLE
[Ingredient] getProgramAccounts

### ISSUE THREAD

**Issue by Jacob-CG** [solana-dev-adv/solana-cookbook#41]
One thing a lot of developer get confused about if [`getProgramAccounts`](https://docs.solana.com/developing/clients/jsonrpc-api#getprogramaccounts).

**Section**: Ingredients

Questions this ingredient should answer:

How does `getProgramAccounts` work?
How do you properly use `dataSlice`?
How do you properly use `filters`?

Check out the structure on ingredients [here](https://github.com/solana-dev-adv/solana-cookbook#ingredients)

**Comment by yihau** [comment]
this part maybe can combine some information about "getAccountInfo" and how data store in to an account.
or we use another page to explain it.

**Comment by Jacob-CG** [comment]
@yihau thinking about having another separate ingredient for accounts in general. Those would go there

**Comment by yihau** [comment]
ok. I think it is also a good way too.

**Comment by bfriel** [comment]
Is anyone working on this? If not, I'd like to @Jacob-CG

**Comment by Jacob-CG** [comment]
@bfriel go for it!

**Comment by bfriel** [comment]
I plan to cover [getParsedProgramAccounts](https://solana-labs.github.io/solana-web3.js/classes/Connection.html#getParsedProgramAccounts) as well since that's replaced `jsonParsed` in web3js. Good with you @Jacob-CG ?

**Comment by Jacob-CG** [comment]
@bfriel Should be fine. I was thinking this section goes more over how `getProgramAccounts` works, what each part of it does. Not married to a specific language. Sure the js library uses multiple functions to present different serialized formats, but that shouldn't matter in the grand scheme of things for an `ingredient`. It could just be a foot note, or an example.

**Comment by bfriel** [comment]
Ahhh gotcha. I'll keep it non-specific when it comes to language then. Thanks!

**Comment by Jacob-CG** [comment]
@bfriel Awesome work!
