### ISSUE TITLE
[Snippet] Get Stake Delegators by Validator

### ISSUE THREAD

**Issue by jacobcreech** [solana-dev-adv/solana-cookbook#45]
A code snippet about getting accounts delegated to a specific vote account would be handy

In other words, get all accounts that are delegating their stake to a specific validator

**Comment by yihau** [comment]
I think this part can melt into a sub part of #41 
also can make more examples like get token account by mint, get mint account by token account ... and so on.
WDYT

**Comment by Jacob-CG** [comment]
It could be as an example, but it should be ok to have it duplicated across ingredients and recipes. We could also link to it from the ingredient

The staking recipe should definitely have this though

**Comment by jacobcreech** [comment]
Closed with #147
