### ISSUE TITLE
[Previews] Add previews to account section

### ISSUE THREAD

**Issue by Jacob-CG** [solana-dev-adv/solana-cookbook#54]
Previews were added recently. Let's clean up the accounts section and add previews to everything.

Example of how it was done for [local development section](https://github.com/solana-dev-adv/solana-cookbook/commit/32098fc2feeb07e44b5dce0e6adbfc2b7f894d12)

**Comment by silvestrevivo** [comment]
@Jacob-CG I can take this one too.
