### ISSUE TITLE
[Preview] Add previews to staking section

### ISSUE THREAD

**Issue by Jacob-CG** [solana-dev-adv/solana-cookbook#56]
Previews were added recently. Let's clean up the staking section and add previews to everything.

Example of how it was done for [local development section](https://github.com/solana-dev-adv/solana-cookbook/commit/32098fc2feeb07e44b5dce0e6adbfc2b7f894d12)

**Comment by silvestrevivo** [comment]
@Jacob-CG I can take this one if it is ok.
