### ISSUE TITLE
[Recipe] Staking

### ISSUE THREAD

**Issue by Jacob-CG** [solana-dev-adv/solana-cookbook#6]
Add Staking section that includes the following:
- Get Current Validators
- Create Stake Account
- Delegate specified stake amount
- Deactivate Stake
- Withdraw stake

**Comment by bfriel** [comment]
Can I take a stab at this?

**Comment by Jacob-CG** [comment]
@bfriel Go right ahead. There are a lot of resources [here](https://docs.solana.com/developing/clients/javascript-reference#staking) that will be a good start.
