### ISSUE TITLE
[Snippet] Create PDA

### ISSUE THREAD

**Issue by Jacob-CG** [solana-dev-adv/solana-cookbook#68]
Add creating a PDA under the accounts section. Should be similar to signing with a pda, just instead using `create_account`

**Comment by neerajajaja** [comment]
hey can I get assigned to this?

**Comment by Jacob-CG** [comment]
@neerajajaja Sure thing! let me know if you have any questions

**Comment by neerajajaja** [comment]
hey just sent a PR, do let me know of any feedback

**Comment by Jacob-CG** [comment]
@neerajajaja Added my feedback. Looks fantastic!
