### ISSUE TITLE
[SEO] Update Meta Descriptions

### ISSUE THREAD

**Issue by jacobcreech** [solana-dev-adv/solana-cookbook#72]
SEO could be vastly improved on the cookbook by adding a better description meta tag, as well as more meta tags for sharing. While we wait for a logo, we can update the meta tags for the descriptions

**Comment by heyAyushh** [comment]
hey @jacobcreech , how can i start contributing to this?

**Comment by jacobcreech** [comment]
Hey @heyAyushh. We basically need custom meta descriptions for each page that help with SEO. Also, all using the same Twitter card would be fine as well. You can look at how to do this by searching head tags for vuepress v2

**Comment by heyAyushh** [comment]
I’ve started my initial work and i am adding descriptions ( 60-150 words ) to each and every page
