### ISSUE TITLE
[Reference] Anchor

### ISSUE THREAD

**Issue by jacobcreech** [solana-dev-adv/solana-cookbook#87]
We need an Anchor recipe section to talk about anchor specific tricks

Current needs:
- Testing with Anchor
- Logging with Anchor
- Explanation of common error codes

**Comment by neerajajaja** [comment]
hey, if you could break this recipe down into smaller snippets i would love to contribute to some of them!

**Comment by Jacob-CG** [comment]
@neerajajaja Asking for feedback in the Anchor discord to identify the commonly asked questions.

For now here's a few I can think of:
- Testing with Anchor
- Logging with Anchor
- Short explanation and use of `#[derive(Accounts)]`
- Short explanation and use of `#[program]`

**Comment by bfriel** [comment]
I think a list of common error codes and their explanations would also be useful

**Comment by patriciobcs** [comment]
I'm working in:
- Anchor program architecture
  - Short explanation and use of #[program]
  - Short explanation and use of #[derive(Accounts)]
  - Short explanation and use of #[account]
- Calculating Account Space Size using impl space function and the respective sizes for each data type

**Comment by jacobcreech** [comment]
@patriciobcs That's awesome! Looking forward to the PR

**Comment by adityabharadwaj198** [comment]
I'd like to pick up the Testing with Anchor part. I can also pick up Logging with Anchor if someone can help me understand what exactly is required.

**Comment by jacobcreech** [comment]
@adityabharadwaj198 Just additional sections on the current anchor page for each testing and logging. For example, showing example code that would log something in an anchor program, and the subsequent log

**Comment by adityabharadwaj198** [comment]
Right, I'll take these up

**Comment by anoushk1234** [comment]
@jacobcreech can i take up common anchor error codes?

**Comment by jacobcreech** [comment]
@anoushk1234 go ahead!

**Comment by adityabharadwaj198** [comment]
I realize it's a bit late, I was caught up with an illness & work but finally was able to find time to do this

**Comment by jacobcreech** [comment]
@adityabharadwaj198 awesome, thanks!
